name: Deploy to DEV

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Compose down potentially running old version
        run: docker-compose -f app/docker-compose.yml down --remove-orphans --rmi all
      #- name: set env variables
      #  run: |
      #    dbuserdata="/db/user:/var/lib/mysql"
      #    dbcalendardata="/db/calendar:/var/lib/mysql"
      #    dbcanteendata="/db/canteen:/var/lib/mysql"
      #    dbrootpw=${{ secrets.DEV_DB_ROOT_PW }}
      #    dbpasswd=${{ secrets.DEV_DB_PW }}
      #- name: adjust db credentials
      #  run: |
      #    sed -i "s/dummypassword/$dbpasswd/g" ./app/backend/user/src/main/resources/application.properties
      #    sed -i "s/dummypassword/$dbpasswd/g" ./app/backend/calendar/src/main/resources/application.properties
      #    sed -i "s/dummypassword/$dbpasswd/g" ./app/backend/canteen/src/main/resources/application.properties
      #    sed -i "s/dummypassword/$dbpasswd/g" ./app/docker-compose.yml
      #    sed -i "s/dummyrootpassword/$dbrootpw/g" ./app/docker-compose.yml
      #- name: enable database persistence
      #  run: |
      #    sed -i "s/#replaceforpersistenceUserDB/$dbuserdata/g" ./app/docker-compose.yml
      #    sed -i "s/#replaceforpersistenceCalendarDB/$dbcalendardata/g" ./app/docker-compose.yml
      #    sed -i "s/#replaceforpersistenceCanteenDB/$dbcanteendata/g" ./app/docker-compose.yml
      - name: Compose Up
        run: docker-compose -f app/docker-compose.yml up --build --force-recreate -d
