name: deploy to dev

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Compose down potentially running old version
        run: docker-compose -f app/docker-compose.yml down --remove-orphans --rmi all
      - name: set env variables
        run: |
          dbrootpw= ${{ secrets.DEV_DB_ROOT_PW }}
          dbpasswd= ${{ secrets.DEV_DB_PW }}
          test= ${{ secrets.TEST }}
          echo $test
      - name: adjust db credentials
        run: |
          sed -i 's/dummypassword/${secrets.DEV_DB_PW}/g' ./app/backend/user/src/main/resources/application.properties
          sed -i 's/dummypassword/${secrets.DEV_DB_PW}/g' ./app/backend/calendar/src/main/resources/application.properties
          sed -i 's/dummypassword/${secrets.DEV_DB_PW}/g' ./app/backend/canteen/src/main/resources/application.properties
          sed -i 's/dummypassword/${secrets.DEV_DB_PW}/g' ./app/docker-compose.yml
          sed -i "s/dummyrootpassword/${{secrets.DEV_DB_ROOT_PW}}/g" ./app/docker-compose.yml
      - name: Compose Up
        run: docker-compose -f app/docker-compose.yml up --build --force-recreate -d
