name: Lighthouse

on:
  workflow_run:
    workflows: ["Deploy to DEV"]
    types:
      - completed
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://dhbwcd-dev.mush-it.com
            https://dhbwcd-dev.mush-it.com/calendar
            https://dhbwcd-dev.mush-it.com/canteen/default
            https://dhbwcd-dev.mush-it.com/dualis
            https://dhbwcd-dev.mush-it.com/links
            https://dhbwcd-dev.mush-it.com/news
            https://dhbwcd-dev.mush-it.com/contact
            https://dhbwcd-dev.mush-it.com/settings
          uploadArtifacts: true
          temporaryPublicStorage: true